"""mvp schema 

Revision ID: 34485d8e00b1
Revises: 689280613890
Create Date: 2026-01-22 17:41:32.540061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '34485d8e00b1'
down_revision: Union[str, Sequence[str], None] = '689280613890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('name', sa.String(), nullable=False))
    op.add_column('artists', sa.Column('followers', sa.String(), nullable=True))
    op.add_column('artists', sa.Column('long_bio', sa.Text(), nullable=True))
    op.add_column('artists', sa.Column('image', sa.String(), nullable=True))
    op.add_column('artists', sa.Column('cover_image', sa.String(), nullable=True))
    op.add_column('artists', sa.Column('social_links', sa.JSON(), nullable=True))
    op.add_column('artists', sa.Column('stats', sa.JSON(), nullable=True))
    op.drop_column('artists', 'profile_image')
    op.drop_column('artists', 'stage_name')
    op.drop_column('artists', 'real_name')
    op.add_column('venues', sa.Column('type', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('website', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('venues', sa.Column('reviews_count', sa.Integer(), nullable=True))
    op.add_column('venues', sa.Column('hours', sa.JSON(), nullable=True))
    op.add_column('venues', sa.Column('amenities', sa.JSON(), nullable=True))
    op.add_column('venues', sa.Column('images', sa.JSON(), nullable=True))
    op.add_column('venues', sa.Column('capacity', sa.Integer(), nullable=True))
    op.drop_column('venues', 'location_name')
    op.drop_column('venues', 'cover_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('cover_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('venues', sa.Column('location_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('venues', 'capacity')
    op.drop_column('venues', 'images')
    op.drop_column('venues', 'amenities')
    op.drop_column('venues', 'hours')
    op.drop_column('venues', 'reviews_count')
    op.drop_column('venues', 'rating')
    op.drop_column('venues', 'website')
    op.drop_column('venues', 'phone')
    op.drop_column('venues', 'type')
    op.add_column('artists', sa.Column('real_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('stage_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('artists', sa.Column('profile_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('artists', 'stats')
    op.drop_column('artists', 'social_links')
    op.drop_column('artists', 'cover_image')
    op.drop_column('artists', 'image')
    op.drop_column('artists', 'long_bio')
    op.drop_column('artists', 'followers')
    op.drop_column('artists', 'name')
    # ### end Alembic commands ###
