"""added attributes in Event Table

Revision ID: 689280613890
Revises: 42ee97d45c5a
Create Date: 2026-01-21 20:48:23.714713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '689280613890'
down_revision: Union[str, Sequence[str], None] = '42ee97d45c5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('genre', sa.String(), nullable=True))
    op.add_column('events', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('events', sa.Column('door_time', sa.Time(), nullable=True))
    op.add_column('events', sa.Column('age_restriction', sa.String(), nullable=True))
    op.add_column('events', sa.Column('is_free_event', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('ticket_tiers', sa.JSON(), nullable=True))
    op.add_column('events', sa.Column('artist_name', sa.String(), nullable=True))
    op.add_column('events', sa.Column('artist_bio', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('social_links', sa.JSON(), nullable=True))
    op.add_column('events', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.drop_column('events', 'status')
    op.drop_column('events', 'music_type')
    op.drop_column('events', 'entry_fee')
    op.drop_column('events', 'event_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('entry_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('music_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('events', 'is_published')
    op.drop_column('events', 'social_links')
    op.drop_column('events', 'artist_bio')
    op.drop_column('events', 'artist_name')
    op.drop_column('events', 'ticket_tiers')
    op.drop_column('events', 'is_free_event')
    op.drop_column('events', 'age_restriction')
    op.drop_column('events', 'door_time')
    op.drop_column('events', 'date')
    op.drop_column('events', 'genre')
    # ### end Alembic commands ###
