"""association tables 

Revision ID: 7d99aa3e537a
Revises: 5d169225137f
Create Date: 2026-02-06 17:18:08.992399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '7d99aa3e537a'
down_revision: Union[str, Sequence[str], None] = '5d169225137f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_follow_artist',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('artist_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('user_follow_venue',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('venue_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], )
    )
    op.add_column('artists', sa.Column('followers_count', sa.String(), nullable=True))
    op.drop_column('artists', 'followers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('followers', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('artists', 'followers_count')
    op.drop_table('user_follow_venue')
    op.drop_table('user_follow_artist')
    # ### end Alembic commands ###
